---
# Safety Security and License Configuration file
# We recommend checking this file into your source control in the root of your
# Python project If this file is named .safety-policy.yml and is in the same
# directory where you run `safety check` it will be used by default.
# Otherwise, you can use the flag `safety check --policy-file
# <path-to-this-file>` to specify a custom location and name for the file. To
# validate and review your policy file, run the validate command: `safety
# validate policy_file --path <path-to-this-file>`
security:  # configuration for the `safety check` command
  ignore-vulnerabilities:
    # Here you can list multiple specific vulnerabilities you want to ignore
    # (optionally for a time period)
    # We recommend making use of the optional `reason` and `expires` keys for
    # each vulnerability that you ignore.

    51668:  # Vulnerability found in sqlalchemy version <2.0.0b1
      reason: |
        we don't use the sqlalchemy, it's brought in by the fastapi-utils

      # datetime string - date this ignore will expire, best practice to use
      # this variable
      expires: '2024-12-31'
