consumer_key = 'fake_consumer_key'
consumer_secret = 'fake_consumer_secret'
access_token = 'fake_access_token'
access_token_secret = 'fake_access_secret'
tweet_at = '12:34'
tweet_at_timezone = 'UTC'
positive_tweet = 'yes'
negative_tweet = 'no'
state_file_path = '<will_be_replaced_by_tempfile>'
