---
name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: '3.11', os: 'ubuntu-latest', session: 'safety'}
          - {python: '3.11', os: 'ubuntu-latest', session: 'bandit'}
          - {python: '3.11', os: 'ubuntu-latest', session: 'test'}
          # 3.10 not working with github env, need deep dive
          #   [VirtualenvCreateError]: Can't resolve python interpreter
          # - {python: '3.10', os: 'ubuntu-latest', session: 'test'}
          - {python: '3.12', os: 'ubuntu-latest', session: 'test'}
          # - {python: '3.11', os: 'windows-latest', session: 'test'}
          # - {python: '3.11', os: 'macos-latest', session: 'test'}

    env:
      NOXSESSION: ${{ matrix.session }}
      FORCE_COLOR: '1'
      PRE_COMMIT_COLOR: 'always'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }} and pdm
        id: setup-pdm
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: |
          pip install -U pip
          pip --version

      - name: Install Nox
        run: |
          pipx install \
            --python "${{ steps.setup-pdm.outputs.python-path }}" \
            --pip-args=-U nox
          nox --version

      - name: Run Nox
        run: |
          nox --python=${{ matrix.python }}

      - name: Upload coverage data
        if: always() && matrix.session == 'test'
        uses: 'actions/upload-artifact@v3'
        with:
          name: coverage-data
          path: '.coverage.*'

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11 and pdm
        id: setup-pdm
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: |
          pip install -U pip
          pip --version

      - name: Install Nox
        run: |
          pipx install \
            --python "${{ steps.setup-pdm.outputs.python-path }}" \
            --pip-args=-U nox
          nox --version

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data

      - name: Combine coverage data and display human readable report
        run: |
          nox --session=coverage \
            --python=3.11

      - name: Create coverage report
        run: |
          nox --session=coverage \
            --python=3.11 \
            -- xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          verbose: true
